import ProjectDescription
import DependencyPlugin

let workspace = Workspace(
  name: "Chatty",
  projects: ["Projects/*"],
  schemes: [
      Scheme(
        name: "Chatty-Release",
        buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Chatty-Release")]),
        runAction: .runAction(configuration: .release),
        archiveAction: .archiveAction(configuration: .release),
        profileAction: .profileAction(configuration: .release),
        analyzeAction: .analyzeAction(configuration: .release)
      ),
      Scheme(
        name: "Chatty-Debug",
        buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Chatty-Debug")]),
        runAction: .runAction(configuration: .debug),
        archiveAction: .archiveAction(configuration: .debug),
        profileAction: .profileAction(configuration: .debug),
        analyzeAction: .analyzeAction(configuration: .debug)
      )
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
