# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

APP_NAME = "Chatty"
SCHEME = "Chatty-QA"
BUNDLE_ID = "org.chattylab.chatty"

KEYCHAIN_NAME = ENV["KEYCHAIN_NAME"]
KEYCHAIN_PASSWORD = ENV["KEYCHAIN_PASSWORD"]

default_platform(:ios)

platform :ios do
  # ✅ 인증서를 키체인에 저장
  desc "Save To Keychain"
  lane :set_keychain do |options|
    create_keychain(
      name: "#{KEYCHAIN_NAME}",
      password: "#{KEYCHAIN_PASSWORD}",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    import_certificate(
      certificate_path: "Tuist/Signing/release.cer",
      keychain_name: "#{KEYCHAIN_NAME}",
      keychain_password: "#{KEYCHAIN_PASSWORD}"
    )

    import_certificate(
      certificate_path: "Tuist/Signing/release.p12",
      keychain_name: "#{KEYCHAIN_NAME}",
      keychain_password: "#{KEYCHAIN_PASSWORD}"
    )

    install_provisioning_profile(path: "Tuist/Signing/#{APP_NAME}-QA.Debug.mobileprovision")
  end

  # ✅ 테스트 플라이트 업로드
  desc "Push to TestFlight"
  lane :tf do |options|
    # ✅ 앱스토어 커넥트 키 연결
    app_store_connect_api_key(is_key_content_base64: true, in_house: false)

    # ✅ 빌드 넘버 증가
    increment_build_number(
      xcodeproj: "Projects/App/#{APP_NAME}.xcodeproj",
      build_number: latest_testflight_build_number + 1
    )

    # ✅ 빌드
    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{SCHEME}",
      export_method: "app-store"
    )

    # ✅ 테스트 플라이트 업로드
    upload_to_testflight(skip_waiting_for_build_processing: true)

    # ✅ 버전 및 빌드 번호 가져오기
    version_number = get_version_number(xcodeproj: "#{APP_NAME}.xcodeproj", target: "Chatty-Release")
    build_number = get_build_number.to_i

    # ✅ 슬랙으로 배포 완료 알림 보내기
    slack(
      username: "Fastlane",
      message: "🎉 배포 완료 🎉",
      icon_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/App_Store_%28iOS%29.svg/1024px-App_Store_%28iOS%29.svg.png",
      slack_url: "https://hooks.slack.com/services/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",
      payload: { "Version": version_number + "(" + build_number.to_s + ")" }
    )
  end
end
